export type TAppDenom =
  | 'SY-AaveUSDC'
  | 'aUSDC'
  | 'ezETH'
  | 'eEth'
  | 'dUSDC'
  | 'SY rsETH'
  | 'SY weETH'
  | 'SY Renzo ezETH'
  | 'AaveUSDC'
  | 'AaveWETH'
  | 'LP - aUSDC'
  | 'USDC (arb1)'
  | 'YT-aUSDC'
  | 'aArbUSDC'
  | 'weETH'
  | 'YT - aUSDC'
  | 'PT - aUSDC'
  | 'USDC(arb1)'
  | 'USDCARB1'
  | 'WBTC'
  | 'ETH'
  | 'wstETH'
  | 'WETH'
  | 'USDT'
  | 'BUSD'
  | 'CAKE'
  | 'Cake'
  | 'USDC'
  | 'WBNB'
  | 'TRAVA'
  | 'ARB'
  | 'BNB'
  | 'TCV'
  | 'PT - eEth'
  | 'PT - dUSDC'
  | 'PT - ezETH'
  | 'YT - eEth'
  | 'YT - dUSDC'
  | 'YT - ezETH'
  | 'PT - AaveUSDC'
  | 'YT - AaveUSDC'
  | 'PT - AaveWETH'
  | 'YT - AaveWETH'
  | 'LP - aUSDC'
  | 'LP - dUSDC'
  | 'LP - ezETH'
  | 'LP - eEth'
  | 'LP - AaveUSDC'
  | 'LP - AaveWETH'
  | 'TCP'
  | 'SY-AaveWETH';
